name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14, 16, 18]
        include:
          - os: macos-latest
            node_version: 16
          - os: macos-latest
            node_version: 18
          - os: windows-latest
            node_version: 16
          - os: windows-latest
            node_version: 18
      fail-fast: false

    name: 'Build & Unit Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm
        uses: npm/action-setup@v2.2.2
        with:
          version: 7

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Install deps
        run: npm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    name: 'Lint: node-18, ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install npm
        uses: npm/action-setup@v2.2.2
        with:
          version: 7

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm prettier --check .

  ts-check-scripts:
    runs-on: ubuntu-latest
    name: 'TS-Check Scripts: node-18, ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install npm
        uses: npm/action-setup@v2.2.2
        with:
          version: 7

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Check scripts
        run: npm run ts-check:scripts

  ts-check-tests:
    runs-on: ubuntu-latest
    name: 'TS-Check Tests: node-18, ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install npm
        uses: npm/action-setup@v2.2.2
        with:
          version: 7

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Check tests
        run: npm run ts-check:tests