on:
  push:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: 'Codecov: ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
          fail_ci_if_error: true