on:
  push:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: 'Codecov'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install deps
        uses: actions/setup-node@v3
        with:
            node-version: 16
      - run: npm ci

      - name: Run tests with coverage
      - run: npm t -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          fail_ci_if_error: true